### ISSUE TITLE
按照步骤1里的四个命令弄  结果最后一个，运行一段时间后报错了，不动了

### ISSUE THREAD

**Issue by moxueyihen** [ykfe/imove#93]
tsc --emitDeclarationOnly
[1] (node:23196) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at F:\web前端\JS\imove\imove\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (F:\web前端\JS\imove\imove\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
[1]     at F:\web前端\JS\imove\imove\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:189:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (F:\web前端\JS\imove\imove\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
[1]     at _next (F:\web前端\JS\imove\imove\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[1] (node:23196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[1] (node:23196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SmallStoneSK** [comment]
@moxueyihen 

这个报错看着像是 umijs 内部报的错，确认下 node_modules 是否都安装成功了。

建议删除 node_modules 后重新安装试试
